### ISSUE TITLE
Imminent crash (Win 7)

### ISSUE THREAD

**Issue by misspierc** [nachmore/unBand#100]
---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'unBand.MainWindow' that matches the specified binding constraints threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Band.Admin, Version=1.3.10218.1, Culture=neutral, PublicKeyToken=608d7da3159f502b' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044) ---> System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

   --- End of inner exception stack trace ---

   at unBand.BandHelpers.BandManager.InitializeCargoLogging()

   at unBand.BandHelpers.BandManager.Create() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:line 157

   at unBand.MainWindow..ctor() in d:\codesanity\oss\unBand\src\unBand\MainWindow.xaml.cs:line 48

   --- End of inner exception stack trace ---

   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)

   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)

   at System.Windows.Application.DoStartup()

   at System.Windows.Application.<.ctor>b__1(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
Aceptar   
---------------------------

**Comment by jehy** [comment]
Try compiled version with fixes from https://github.com/robsonj/unBand : https://github.com/jehy/unBand/releases/tag/v0.72.xxx
