### ISSUE TITLE
Crash when downloading - unknown event type (golf)

### ISSUE THREAD

**Issue by briankavanaugh** [nachmore/unBand#102]
---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.Collections.Generic.KeyNotFoundException: Unknown event type: Microsoft.Khronos.Cloud.Ods.Data.Entities.GolfEventDTO

   at unBand.Cloud.BandEventBase.FromDynamic(Object rawBandEvent) in d:\codesanity\oss\unBand\src\unBand.Cloud\Events\BandEventBase.cs:line 132

   at unBand.Cloud.BandCloudClient.<GetEvents>d__27.MoveNext() in d:\codesanity\oss\unBand\src\unBand.Cloud\BandCloudClient.cs:line 197

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.CloudHelpers.BandCloudManager.<LoadEvents>d__0.MoveNext() in d:\codesanity\oss\unBand\src\unBand\CloudHelpers\BandCloudManager.cs:line 140

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.pages.ActivityLogPage.<LoadEvents>d__b.MoveNext() in d:\codesanity\oss\unBand\src\unBand\pages\ActivityLogPage.xaml.cs:line 176

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.pages.ActivityLogPage.<btnLoadEvents_Click>d__8.MoveNext() in d:\codesanity\oss\unBand\src\unBand\pages\ActivityLogPage.xaml.cs:line 171

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by briankavanaugh** [comment]
I have added the code for this and made a couple of changes for the newest version of the Microsoft Sync app to a fork off of robsonj's fork.

**Comment by Roadstergal** [comment]
I just opened an Issue for a similar problem - Microsoft added the new Hike event, and now that I have a Hike on my band, Unband crashes trying to read the activities.
