### ISSUE TITLE
Imminent Crash upon first execution

### ISSUE THREAD

**Issue by boobboo** [nachmore/unBand#121]
Hi 

I got this crash message when trying to use with my Microsoft Band 2 - I tried running with and without the Microsoft Band Sync program running

Thanks

Chris
---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'unBand.MainWindow' that matches the specified binding constraints threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Band.Admin, Version=1.3.10218.1, Culture=neutral, PublicKeyToken=608d7da3159f502b' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044) ---> System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

   --- End of inner exception stack trace ---

   at unBand.BandHelpers.BandManager.InitializeCargoLogging()

   at unBand.BandHelpers.BandManager.Create() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:line 157

   at unBand.MainWindow..ctor() in d:\codesanity\oss\unBand\src\unBand\MainWindow.xaml.cs:line 48

   --- End of inner exception stack trace ---

   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)

   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)

   at System.Windows.Application.DoStartup()

   at System.Windows.Application.<.ctor>b__1(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by ublish** [comment]
I received the identical error using Windows 10

**Comment by chetsmith** [comment]
I received the identical error. Windows 10

**Comment by Capro** [comment]
I am seeing the same error. Also Windows 10.

**Comment by KaiserKai** [comment]
Same here. Win10. Would love to use this app, it solves a problem I cant otherwise overcome.

**Comment by acydlord** [comment]
Looks like Microsoft Band Sync for windows 10 does not have the Microsoft.Cargo.Client.Desktop8.dll which is causing the crash on start-up.

**Comment by dineshpatnaik** [comment]
Received the same error on Windows 10.

**Comment by ah80** [comment]
Same error here. Windows 10 on a Surface Pro Laptop with a MS Band 1. Latest desk sync is installed. App crashes with the message beneath:

---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'unBand.MainWindow' that matches the specified binding constraints threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Band.Admin, Version=1.3.10218.1, Culture=neutral, PublicKeyToken=608d7da3159f502b' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044) ---> System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

   --- End of inner exception stack trace ---

   at unBand.BandHelpers.BandManager.InitializeCargoLogging()

   at unBand.BandHelpers.BandManager.Create() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:line 157

   at unBand.MainWindow..ctor() in d:\codesanity\oss\unBand\src\unBand\MainWindow.xaml.cs:line 48

   --- End of inner exception stack trace ---

   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)

   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)

   at System.Windows.Application.DoStartup()

   at System.Windows.Application.<.ctor>b__1_0(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by ckayfish** [comment]
Same as others. Windows 7, latest MS band Sync (1.3.20329.1). Just downloaded Unband.

**Comment by lukedude** [comment]
I cloned this repo to see if there was something simple that could be done to get this working with the new version of Microsoft.Band.Admin, but MSFT changed many of their APIs including sealing off some of them. Large chunks of unBand would need to be rewritten to work with the new APIs.

If it were possible to find an old version of Microsoft Band Sync, that would fix things. I have not been able to find one.
https://www.microsoft.com/en-us/download/details.aspx?id=44579%20

On the plus side, there is a fully supported Microsoft.Band sdk here so retooling unband might not be that hard... https://www.nuget.org/packages/Microsoft.Band/
