### ISSUE TITLE
Application crash - Windows 8.1 / MS Surface Pro 3

### ISSUE THREAD

**Issue by ianmcs** [nachmore/unBand#14]
This occured from the first run after install and every subsequent attempt to launch, it has never worked.

If MS Band Sync is running, the crash occurs as soon as I close MS Band Sync (with Unband running)

---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

Microsoft.Cargo.Client.CargoTransportException: Cannot read data from the stream. ---> System.ComponentModel.Win32Exception: WinUsb_ReadPipe failed.

   at Microsoft.Cargo.Client.Desktop.WinUsbStream.Read(Byte[] buffer, Int32 offset, Int32 count)

   at Microsoft.Cargo.Client.CargoStreamReader.Read(Byte[] destination, Int32 offset, Int32 count)

   at Microsoft.Cargo.Client.CargoCommandReader.Read(Byte[] buffer, Int32 offset, Int32 count)

   at Microsoft.Cargo.Client.CargoCommandReader.ReadToEnd(Byte[] buffer, Int32 offset)

   --- End of inner exception stack trace ---

   at Microsoft.Cargo.Client.CargoCommandReader.ReadToEnd(Byte[] buffer, Int32 offset)

   at Microsoft.Cargo.Client.CargoClient.ProtocolRead(UInt16 commandId, Byte[] argBuf, Byte[] result, Int32 offset, Int32 bytesToRead, Int32 timeout, CommandStatusHandling statusHandling)

   at Microsoft.Cargo.Client.CargoClient.GetMeTileImage()

   at unBand.BandHelpers.BandTheme.<Init>b__1()

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by nachmore** [comment]
Thanks for the report - this is coming directly from the Band library, and not from unBand's code. Does the MS Sync client work correctly(i.e. can you sync)?

**Comment by ianmcs** [comment]
Hi,

Yep, the MS sync client works perfectly.

This crash happens when the MS sync client is closed.

Thx

**Comment by nachmore** [comment]
The crash happens when the Sync client closes because that's when unBand tries to connect to the Band (the Band can only be connected to by one application at a time, so unBand waits for the Sync client to close and then attempts to connect using the Band's library).

Can you try closing the Sync client before connecting the Band to the computer and then opening unBand?

**Comment by ianmcs** [comment]
Yeh, it happens then too. Literally every time I run unband. I'll run it
again with the Sync client closed and send you the crash data.

**Comment by ianmcs** [comment]
OK, my repro steps:

1. Reboot.
2. Quit MS Sync, MS Band is NOT connected.
3. Start Unband.
4. "Now is the time to connect your band..." etc.
5. Connect band.
6. Crash.
7. C+P.
8. Paste in here.

I can reproduce this at will, every time.

hope that helps!

---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to
crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and
then paste into a new bug at https://github.com/nachmore/unBand/issues.

Microsoft.Cargo.Client.CargoTransportException: Cannot read data from the
stream. ---> System.ComponentModel.Win32Exception: WinUsb_ReadPipe failed.

   at Microsoft.Cargo.Client.Desktop.WinUsbStream.Read(Byte[] buffer, Int32
offset, Int32 count)

   at Microsoft.Cargo.Client.CargoStreamReader.Read(Byte[] destination,
Int32 offset, Int32 count)

   at Microsoft.Cargo.Client.CargoCommandReader.Read(Byte[] buffer, Int32
offset, Int32 count)

   at Microsoft.Cargo.Client.CargoCommandReader.ReadToEnd(Byte[] buffer,
Int32 offset)

   --- End of inner exception stack trace ---

   at Microsoft.Cargo.Client.CargoCommandReader.ReadToEnd(Byte[] buffer,
Int32 offset)

   at Microsoft.Cargo.Client.CargoClient.ProtocolRead(UInt16 commandId,
Byte[] argBuf, Byte[] result, Int32 offset, Int32 bytesToRead, Int32
timeout, CommandStatusHandling statusHandling)

   at Microsoft.Cargo.Client.CargoClient.GetMeTileImage()

   at unBand.BandHelpers.BandTheme.<Init>b__1()

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate
callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object
source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK
---------------------------

**Comment by nachmore** [comment]
Interesting - thanks for the steps. I'm going to add some extra logging to unBand to see if we can try to figure out what's going on here, since it's obviously not affecting the Sync client, but (in theory) we're doing the same thing. I'll comment on this issue again when the new version makes its way out with the logging.

**Comment by ianmcs** [comment]
OK, no problems.

**Comment by nachmore** [comment]
Please reopen if this is still happening with the new version that uses the new Band dlls.
