### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by pilulkin** [nachmore/unBand#27]
---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Cargo.Client.Desktop8, Version=1.3.1106.2, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

File name: 'Microsoft.Cargo.Client.Desktop8, Version=1.3.1106.2, Culture=neutral, PublicKeyToken=null'

   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)

   at System.Reflection.RuntimePropertyInfo.get_Signature()

   at System.Reflection.RuntimePropertyInfo.get_PropertyType()

   at MS.Internal.Data.PropertyPathWorker.GetInfo(Int32 k, Object item, SourceValueState& svs)

   at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)

   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)

   at MS.Internal.Data.ClrBindingWorker.AttachDataItem()

   at System.Windows.Data.BindingExpression.Activate(Object item)

   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)

   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)

   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)

   at MS.Internal.Data.DataBindEngine.Run(Object arg)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

WRN: Assembly binding logging is turned OFF.

To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.

To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

---------------------------
OK   
---------------------------

**Comment by nachmore** [comment]
Thanks for the report - do you have the Desktop Microsoft Band Sync app installed?

**Comment by pilulkin** [comment]
Yes, it worked when i closed it completely. User error.
