### ISSUE TITLE
Imminent Crash

### ISSUE THREAD

**Issue by adescre** [nachmore/unBand#36]
---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.ComponentModel.Win32Exception (0x80004005): WinUsb_ReadPipe failed.

   at Microsoft.Cargo.Client.Desktop.WinUsbStream.Read(Byte[] buffer, Int32 offset, Int32 count)

   at Microsoft.Cargo.Client.CargoStreamReader.ReadToBuffer()

   at Microsoft.Cargo.Client.CargoStreamReader.ReadToBufferMinimum(Int32 minCount)

   at Microsoft.Cargo.Client.CargoStreamReader.ReadStruct[T](T& structure)

   at Microsoft.Cargo.Client.CargoCommandReader.ReadStruct[T](T& structure)

   at Microsoft.Cargo.Client.CargoClient.AppListGet(UInt16 commandId)

   at Microsoft.Cargo.Client.CargoClient.InstalledAppListGet()

   at Microsoft.Cargo.Client.CargoClient.GetStartStrip()

   at Microsoft.Cargo.Client.CargoClient.<GetStartStripAsync>b__232()

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.Cargo.Client.CargoClient.<GetStartStripAsync>d__233.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandTiles.<Init>d__1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by nachmore** [comment]
Unfortunately this is coming directly from the Band - if this happens often can you tell me what you were doing at the time and whether you've tried other USB ports? Thanks!

**Comment by nachmore** [comment]
Please reopen if this is still happening on the latest version which uses the new Band dlls.

**Comment by EphraimB** [comment]
It's not working with the new Band dlls either

**Comment by nachmore** [comment]
@EphraimB I don't believe your issue is related to the stack in this bug. Please open a separate bug with your stack (and a list of your tiles).
