### ISSUE TITLE
Support the new Desktop app

### ISSUE THREAD

**Issue by nachmore** [nachmore/unBand#41]
Microsoft have refactored a lot of their Desktop code, which breaks unBand. Time to update some references :)

**Comment by myband6** [comment]
Do you have an older version of "Microsoft Band Sync" that works with the current "unBand"? If you do, can you please share it? It would be much appreciated. :)

**Comment by nachmore** [comment]
Sadly I can't redistribute Microsoft Copyright code :(

**Comment by myband6** [comment]
aaww, Totally understand. You know which version of MS Band Sync works with "unBand"? Maybe I can find it elsewhere? ;)

**Comment by myband6** [comment]
Otherwise, do you know the approximate time that a working version will be updated? :)

**Comment by EphraimB** [comment]
How long will the new version be out? Any new features or just making it compatible with the new Microsoft Band Sync update?

**Comment by nachmore** [comment]
You can follow along with the commits which are pretty much coming in realtime (I forgot to tag the last one (f4d14773529b3c87107ebec1c00b445dd84375db)). I'm hoping to push this out tonight.

The only new feature will be support for Bike events, though I'm hoping to integrate the two pull requests (Map + TCX export), so there's that as well :)

**Comment by EphraimB** [comment]
Can you add the option that I badly want (which is listed in issue #44)?

**Comment by EphraimB** [comment]
When will this be done? And why did you reopen this issue?

**Comment by nachmore** [comment]
it will be done when it's ready.

For reopening rationale, see the commits that followed the reopening.

**Comment by EphraimB** [comment]
Now this is coming up:
---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.ArgumentException: name cannot have length 0.

   at Microsoft.Band.Admin.CargoStrapp.SetName(Guid id, String name)

   at Microsoft.Band.Admin.CargoStrapp..ctor(Guid id, String name, StrappSettings strappSettings, IList`1 images, UInt32 tileImageIndex, IList`1 layouts, Nullable`1 badgeImageIndex)

   at Microsoft.Band.Admin.TileDataExtensions.ToCargoStrapp(TileData data, TileIconRleData icon)

   at Microsoft.Band.Admin.CargoClient.StrappStructToClass(List`1 list)

   at Microsoft.Band.Admin.CargoClient.GetStartStrip()

   at Microsoft.Band.Admin.CargoClient.<GetStartStripAsync>b__251()

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.Band.Admin.CargoClient.<GetStartStripAsync>d__252.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandTiles.<InitAsync>d__1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandManager.<>c__DisplayClassb.<<ConnectDevice>b__9>d__d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by DaStivi** [comment]
is there any news on this one??? i tried to copy the 4 new dll to the unband install directory but as it seams the updated code is not compiled and installed with the oneclick installer????

**Comment by DaStivi** [comment]
ok i guess the "new" sync client should be supported allready...  but i guess there is now a new new version available... as the band.admin.dll has now this version number: 1.3.11004.2 and the error messages states that is searches for 1.3.10218.1
