### ISSUE TITLE
Imminent Crash: name cannot have length 0

### ISSUE THREAD

**Issue by EphraimB** [nachmore/unBand#46]
---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.ArgumentException: name cannot have length 0.

   at Microsoft.Band.Admin.CargoStrapp.SetName(Guid id, String name)

   at Microsoft.Band.Admin.CargoStrapp..ctor(Guid id, String name, StrappSettings strappSettings, IList`1 images, UInt32 tileImageIndex, IList`1 layouts, Nullable`1 badgeImageIndex)

   at Microsoft.Band.Admin.TileDataExtensions.ToCargoStrapp(TileData data, TileIconRleData icon)

   at Microsoft.Band.Admin.CargoClient.StrappStructToClass(List`1 list)

   at Microsoft.Band.Admin.CargoClient.GetStartStrip()

   at Microsoft.Band.Admin.CargoClient.<GetStartStripAsync>b__251()

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.Band.Admin.CargoClient.<GetStartStripAsync>d__252.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandTiles.<InitAsync>d__1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandManager.<>c__DisplayClassb.<<ConnectDevice>b__9>d__d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by nachmore** [comment]
Thanks for the bug. Since this is coming directly from the Band and not from my code I'm going to need some more details to try and repro this issue. Can you tell me:

1. The version of the Desktop sync app
2. What tiles you have installed so that I can setup a Band to match what you have

**Comment by EphraimB** [comment]
1) 1.3.10218.1
2) Run, Sleep, Exercise, Guided workout, Alarm & Timer, UV, Calendar, Mail, Twitter, Weather, Finance, Notifications Center

**Comment by nachmore** [comment]
Looks like this is a Band issue - see: http://www.reddit.com/r/MicrosoftBand/comments/2xe75w/unband_updated_but_i_have_a_crash/cozbvdw

Suggested workaround: remove your tiles and then readd them from your Phone

Please let me know if this fixes the issue for you.

**Comment by nachmore** [comment]
re-pinging this item - does the workaround work? Thanks!

**Comment by toledospod** [comment]
Nachmore, just had the same issue myself and I have an iPhone. Tried the workaround and then launching UnBand, worked for me :) Thanks!

**Comment by nachmore** [comment]
Thanks for the confirmation - I'm going to close this for now, if you still run into this and the workaround doesn't work, please reopen. Thanks!
