### ISSUE TITLE
Crash: Could not find Microsoft.Band.Admin

### ISSUE THREAD

**Issue by ChargePositive** [nachmore/unBand#47]
---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'unBand.MainWindow' that matches the specified binding constraints threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Band.Admin, Version=1.3.10218.1, Culture=neutral, PublicKeyToken=608d7da3159f502b' or one of its dependencies. The system cannot find the file specified.

   at unBand.BandHelpers.BandManager.InitializeCargoLogging()

   at unBand.BandHelpers.BandManager.Create()

   at unBand.MainWindow..ctor()

   --- End of inner exception stack trace ---

   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)

   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)

   at System.Windows.Application.DoStartup()

   at System.Windows.Application.<.ctor>b__1(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by nachmore** [comment]
Do you have the latest Microsoft Band Sync app installed?
