### ISSUE TITLE
Always crashes on start

### ISSUE THREAD

**Issue by davsug** [nachmore/unBand#55]
---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.ArgumentException: name cannot have length 0.

   at Microsoft.Band.Admin.CargoStrapp.SetName(Guid id, String name)

   at Microsoft.Band.Admin.CargoStrapp..ctor(Guid id, String name, StrappSettings strappSettings, IList`1 images, UInt32 tileImageIndex, IList`1 layouts, Nullable`1 badgeImageIndex)

   at Microsoft.Band.Admin.TileDataExtensions.ToCargoStrapp(TileData data, TileIconRleData icon)

   at Microsoft.Band.Admin.CargoClient.StrappStructToClass(List`1 list)

   at Microsoft.Band.Admin.CargoClient.GetStartStrip()

   at Microsoft.Band.Admin.CargoClient.<GetStartStripAsync>b__251()

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.Band.Admin.CargoClient.<GetStartStripAsync>d__252.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandTiles.<InitAsync>d__1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandManager.<>c__DisplayClassb.<<ConnectDevice>b__9>d__d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

I get that every time I run it.  I have the Band Sync app installed but not running, and I always get this.  It worked perfectly before the new app update.

**Comment by davsug** [comment]
Is it possible to try installing one of the older versions to see if that works?  I was running v .62 before I upgraded today and that one worked perfectly.

**Comment by nachmore** [comment]
Older versions were based off the old Band Desktop Sync App which did not have this bug (the bug is not in unBand). Please remove and readd your tiles to work around this bug, sorry :(

For more information see #53

**Comment by davsug** [comment]
Thanks for the quick reply.  So what do you mean remove & read tiles?  I'm trying to add the customized background & color I had from the older version of Unband.  I had to do a hard reset of my band due to a separate issue, so I can't figure out how to connect to Unband.  Is there something I'm missing?
 
Date: Tue, 3 Mar 2015 19:14:59 -0800

**Comment by davsug** [comment]
never mind.  figured it out and it seems to be working.  Thanks alot
 
Date: Tue, 3 Mar 2015 19:14:59 -0800

**Comment by jinayoon** [comment]
Hey @davsug were you able to get it working? Do you have a copy of the old version of Microsoft Band Sync? I really want to use unBand but I'm getting the common error of crashing on start, and I think it's because I'm using the newer versions of Sync. It doesn't have the Microsoft.Cargo.Client.Desktop8.dll file everyone is talking about.

Thanks!
