### ISSUE TITLE
Crash: WinUsb_ReadPipe failed

### ISSUE THREAD

**Issue by FPrefect61** [nachmore/unBand#56]
I've been getting this crash everytime I connect my Band to my computer (running Windows 7, SP1).  I thought it may be related to the "Microsoft.Cargo.Client.Desktop8.dll" issue so many people have had, but I don't even have that file anywhere on my computer.  Please help!!

---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

Microsoft.Band.BandIOException: WinUsb_ReadPipe failed. ---> System.ComponentModel.Win32Exception: WinUsb_ReadPipe failed.

   at Microsoft.Band.Desktop.WinUsbStream.Read(Byte[] buffer, Int32 offset, Int32 count)

   at Microsoft.Band.CargoStreamReader.Read(Byte[] destination, Int32 offset, Int32 count)

   at Microsoft.Band.CargoStreamReader.ReadExact(Byte[] destination, Int32 offset, Int32 count)

   at Microsoft.Band.CargoCommandReader.ReadToEnd(Byte[] buffer, Int32 offset)

   at Microsoft.Band.BandClient.ProtocolRead(UInt16 commandId, Byte[] argBuf, Byte[] result, Int32 offset, Int32 bytesToRead, Int32 timeout, CommandStatusHandling statusHandling)

   --- End of inner exception stack trace ---

   at Microsoft.Band.BandClient.ProtocolRead(UInt16 commandId, Byte[] argBuf, Byte[] result, Int32 offset, Int32 bytesToRead, Int32 timeout, CommandStatusHandling statusHandling)

   at Microsoft.Band.BandClient.GetMeTileImageInternal(CancellationToken cancel)

   at Microsoft.Band.BandClient.<>c__DisplayClass18.<GetMeTileImageAsync>b__17()

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandTheme.<InitAsync>d__1.MoveNext() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandTheme.cs:line 199

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandManager.<>c__DisplayClassb.<<ConnectDevice>b__9>d__d.MoveNext() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:line 261

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by nachmore** [comment]
That file is no longer included with the Microsoft Band Desktop Sync app - it's now split across multiple files. In general though, if unBand can't find that file then you wouldn't get this error, since it's coming from Band code and not from unBand.

Sadly, there is not much we can do to help with this since this is happening deep in Band code. I'd make sure that the Desktop sync app works correctly and that you've tried different USB ports (since this is a USB error).

Also, can you provide as much information as possible about your system? If you're comfortable sharing the output from "msinfo32 /report [filename]" that would be great, otherwise I'm primarily interested in your OS version as well as if it's 32 or 64 bit. Thanks!

**Comment by nachmore** [comment]
Closing due to inactivity. Please reopen if you have more details. Thanks!
