### ISSUE TITLE
New Issue Experienced

### ISSUE THREAD

**Issue by matthewc01** [nachmore/unBand#63]
Hi, 
I hope this is helpful, let me know if there's anything else I can do to assist however I'm not a coder.
Thanks,
Matthew

---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

Microsoft.Band.BandIOException: Cannot write data to the stream. ---> System.ComponentModel.Win32Exception: WinUsb_WritePipe failed.

   at Microsoft.Band.Desktop.WinUsbStream.Write(Byte[] buffer, Int32 offset, Int32 count)

   at Microsoft.Band.CargoStreamWriter.Flush()

   at Microsoft.Band.Desktop.UsbTransport.WriteCommandPacket(CargoCommand packetHeader, Byte[] argBuf, Boolean flush)

   --- End of inner exception stack trace ---

   at Microsoft.Band.Desktop.UsbTransport.WriteCommandPacket(CargoCommand packetHeader, Byte[] argBuf, Boolean flush)

   at Microsoft.Band.BandClient.ProtocolReadStruct[T](UInt16 commandId, Byte[] argBuf, T& result, Int32 timeout, CommandStatusHandling statusHandling)

   at Microsoft.Band.BandClient.GetRunningFirmwareApp()

   at Microsoft.Band.Admin.BandAdminClientManager.ConcreteConnect(IBandInfo bandInfo)

   at Microsoft.Band.Admin.BandAdminClientManager.<>c__DisplayClass5.<ConnectAsync>b__4()

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.Band.Admin.BandAdminClientManager.<ConnectAsync>d__7.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandManager.<GetUSBBand>d__1c.MoveNext() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:line 302

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandManager.<ConnectDevice>d__10.MoveNext() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:line 0

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandManager.<<Start>b__0>d__4.MoveNext() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:line 206

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by nachmore** [comment]
Is this still happening? This comes directly from the Band, not from unBand so is usually transitory.

**Comment by matthewc01** [comment]
Hi,
Thanks for getting back to me, It does seem to be ok now.
Thanks and sorry for the false positive.
Regards,
Matthew
