### ISSUE TITLE
New crash

### ISSUE THREAD

**Issue by Shuflie** [nachmore/unBand#72]
Crashing when band detected. The Band sync app was updated today which might be the problem, was working before.

---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<UInt32> Microsoft.Band.Admin.CargoClient.GetMaxStrappCountAsync()'.

   at unBand.BandHelpers.BandProperties.<InitAsync>d__0.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)

   at unBand.BandHelpers.BandProperties.InitAsync()

   at unBand.BandHelpers.BandManager.<>c__DisplayClassb.<<ConnectDevice>b__9>d__d.MoveNext() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:line 260

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by robsonj** [comment]
What version of Microsoft.Band.Admin.dll are you using?

**Comment by robsonj** [comment]
Ok, I upgrade my sync pp. A bunch of compile errors agaist the last MS Band dll's to fix. Probably the API changes causing the compilation failure are related to the crash (MissingMethodException).

**Comment by robsonj** [comment]
Submitted pull request with fixes for this...

https://github.com/nachmore/unBand/pull/76

**Comment by morizono** [comment]
I have zero comprehension of .NET, or the Microsoft way of doing things so apologies in advance. I looked at Microsoft.Band.Admin.dll with ILSpy.  The version that works on my computer is 1.3.10302.1, and the Band Sync App was created around March 5th.  The version I downloaded today is 1.3.10423.3 and that App has a file modification date of April 24. 
In the newer Microsoft.Band.Admin.dll under  ICargoClient, there is a GetMaxTileCountAsync, but not a GetMaxStrappCountAsync.  Would replacing MaxStrappCount with MaxTileCount fix this issue?
