### ISSUE TITLE
New crash

### ISSUE THREAD

**Issue by mceza** [nachmore/unBand#75]
---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<UInt32> Microsoft.Band.Admin.CargoClient.GetMaxStrappCountAsync()'.

   at unBand.BandHelpers.BandProperties.<InitAsync>d__0.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)

   at unBand.BandHelpers.BandProperties.InitAsync()

   at unBand.BandHelpers.BandManager.<>c__DisplayClassb.<<ConnectDevice>b__9>d__d.MoveNext() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:line 260

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by mceza** [comment]
Oh sorry, now I see this was reported 13 hours ago too.

**Comment by robsonj** [comment]
Submitted pull request with fixes for this...

https://github.com/nachmore/unBand/pull/76
