### ISSUE TITLE
Crashes right after launching

### ISSUE THREAD

**Issue by Toddard** [nachmore/unBand#80]
Running on Windows 10 tech preview build 10074

=====================

---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<UInt32> Microsoft.Band.Admin.CargoClient.GetMaxStrappCountAsync()'.

   at unBand.BandHelpers.BandProperties.<InitAsync>d__0.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

   at unBand.BandHelpers.BandProperties.InitAsync()

   at unBand.BandHelpers.BandManager.<>c__DisplayClassb.<<ConnectDevice>b__9>d__d.MoveNext() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:line 260

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by robsonj** [comment]
Dupe of https://github.com/nachmore/unBand/issues/77 & https://github.com/nachmore/unBand/issues/75 & https://github.com/nachmore/unBand/issues/72

**Comment by Toddard** [comment]
Sorry for the duplication. I'll try closing the issue.
