### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pszemekd** [nachmore/unBand#82]
On 5th of May 2015

---
## Imminent Crash

An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<UInt32> Microsoft.Band.Admin.CargoClient.GetMaxStrappCountAsync()'.

   at unBand.BandHelpers.BandProperties.<InitAsync>d__0.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)

   at unBand.BandHelpers.BandProperties.InitAsync()

   at unBand.BandHelpers.BandManager.<>c__DisplayClassb.<<ConnectDevice>b__9>d__d.MoveNext() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:line 260

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

**Comment by Dregus311** [comment]
I also experienced this today for the first time. I first experienced in on a new install on my desktop. Thinking it was an install error that caused the overall problem I tried using my Surface 3 as I normally do and the same issue arose.
