### ISSUE TITLE
Imminent crash after band sync app has been closed

### ISSUE THREAD

**Issue by alanajrobinson** [nachmore/unBand#96]
Imminent Crash every time app is launched, and microsoft band sync app has been closed.

Repro steps:
Open unband
Agree to terms
Close microsoft sync app
Imminent crash

---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<UInt32> Microsoft.Band.Admin.CargoClient.GetMaxStrappCountAsync()'.

   at unBand.BandHelpers.BandProperties.<InitAsync>d__0.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)

   at unBand.BandHelpers.BandProperties.InitAsync()

   at unBand.BandHelpers.BandManager.<>c__DisplayClassb.<<ConnectDevice>b__9>d__d.MoveNext() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:line 260

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by alanajrobinson** [comment]
![image](https://cloud.githubusercontent.com/assets/8992921/8011933/0782fb48-0b72-11e5-930d-a68fae1b50fd.png)

**Comment by morizono** [comment]
GetMaxStrappCountAsync no longer exists in the Microsoft Band Sync App DLL. 
The downloadable executable for UnBand is calling that. 
Going to an older version of the health app works. Not too helpful, sorry



-----Original Message-----

**Comment by EinPinsel** [comment]
@morizono Do you have a link for the older version?

**Comment by BilboBagginsEsq** [comment]
Thanks for this app.
it seems like a great idea but I'm unable to use it.
I'm having this same crash at the call for GetMaxStrappCountAsync

Is there a fix available?
