### ISSUE TITLE
Imminent Crash without Microsoft.Cargo.Client.Desktop8.dll 

### ISSUE THREAD

**Issue by shurru** [nachmore/unBand#97]
So I read that to prevent the crash from occurring, I needed to copy Microsoft.Cargo.Client.Desktop8.dll , however I'm having difficulty finding that in the Band Sync file. Is there another .dll file that I can use instead? 
---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<UInt32> Microsoft.Band.Admin.CargoClient.GetMaxStrappCountAsync()'.

   at unBand.BandHelpers.BandProperties.<InitAsync>d__0.MoveNext()

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)

   at unBand.BandHelpers.BandProperties.InitAsync()

   at unBand.BandHelpers.BandManager.<>c__DisplayClassb.<<ConnectDevice>b__9>d__d.MoveNext() in d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:line 260

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by TimC-UK** [comment]
Same problem here. I cannot find Microsoft.Cargo.Client.Desktop8.dll on my machine at all. Tried doing a DOS search across all files and nothing found. Look in Visual Studio and not under references. However, sync app works fine. Had the sync app changed or perhaps different on different OS versions. I'm on Windows 7?

**Comment by BronwenZ** [comment]
+1 Can't find that dll and app crashes on load.

**Comment by BilboBagginsEsq** [comment]
+1, I also can't find this file.

**Comment by jinayoon** [comment]
@shurru @TimC-UK @BronwenZ @BilboBagginsEsq Were any of you able to find this file, or an older version of Band Sync?
