### ISSUE TITLE
No longer being supported?

### ISSUE THREAD

**Issue by SlasherKG** [nachmore/unBand#99]
Seems that the same crashes have been around for months with no fix.
Is this still being updated?

**Comment by jehy** [comment]
Try compiled version with fixes from https://github.com/robsonj/unBand : https://github.com/jehy/unBand/releases/tag/v0.72.xxx

**Comment by ghotz** [comment]
I'm trying the above build and got the following error while trying to export the data:

---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.ArgumentException: Requested value 'NotWorn' was not found.

   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)

   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)

   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)

   at Newtonsoft.Json.Utilities.ConvertUtils.TryConvertInternal(Object initialValue, CultureInfo culture, Type targetType, Object& value)

   at Newtonsoft.Json.Utilities.ConvertUtils.Convert(Object initialValue, CultureInfo culture, Type targetType)

   at Newtonsoft.Json.Linq.JValue.JValueDynamicProxy.TryConvert(JValue instance, ConvertBinder binder, Object& result)

   at CallSite.Target(Closure , CallSite , Object )

   at unBand.Cloud.SleepEventSequenceItem..ctor(JObject json) in d:\tmp\unBand-90ce0a4e155009ddf576043a52cb0a3a465d7d8d\src\unBand.Cloud\Events\SleepEvent.cs:line 52

   at CallSite.Target(Closure , CallSite , Type , Object )

   at unBand.Cloud.SleepEvent.InitFullEventData(JObject json) in d:\tmp\unBand-90ce0a4e155009ddf576043a52cb0a3a465d7d8d\src\unBand.Cloud\Events\SleepEvent.cs:line 134

   at unBand.CloudHelpers.BandEventViewModel.<<LoadFull>b__0>d__2.MoveNext() in d:\tmp\unBand-90ce0a4e155009ddf576043a52cb0a3a465d7d8d\src\unBand\CloudHelpers\BandEventViewModel.cs:line 67

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.CloudHelpers.BandEventViewModel.<LoadFull>d__6.MoveNext() in d:\tmp\unBand-90ce0a4e155009ddf576043a52cb0a3a465d7d8d\src\unBand\CloudHelpers\BandEventViewModel.cs:line 63

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.CloudHelpers.BandCloudManager.<ExportFullEventData>d__23.MoveNext() in d:\tmp\unBand-90ce0a4e155009ddf576043a52cb0a3a465d7d8d\src\unBand\CloudHelpers\BandCloudManager.cs:line 293

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)

   at unBand.pages.ActivityLogPage.<btnExportAll_Click>d__19.MoveNext() in d:\tmp\unBand-90ce0a4e155009ddf576043a52cb0a3a465d7d8d\src\unBand\pages\ActivityLogPage.xaml.cs:line 298

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by jinayoon** [comment]
@jehy Were you able to get this to work? Would you be able to help me?

**Comment by jehy** [comment]
@jinayoon it worked for me, but I needed to use it only once so I won't make new releases.

**Comment by jinayoon** [comment]
@jehy I see, that's a shame :( It does work for a bit, but I get the same crash error as @ghotz posted above. Thanks anyway!
